#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
cd $DIR

if [ "$(uname -m)" = "riscv64" ] || [ "${OPENPILOT_TARGET_ARCH:-}" = "riscv64" ]; then
  export LD_LIBRARY_PATH="$DIR/../../third_party/acados/riscv64/lib:$DIR/../../cereal:$DIR/../../selfdrive/common:$LD_LIBRARY_PATH"
elif [ -d /system ]; then
  if [ -f /TICI ]; then # QCOM2
    export LD_LIBRARY_PATH="/usr/lib/aarch64-linux-gnu:/data/pythonpath/third_party/snpe/larch64:$LD_LIBRARY_PATH"
  else # QCOM
    export LD_LIBRARY_PATH="/data/pythonpath/third_party/snpe/aarch64/:$LD_LIBRARY_PATH"
  fi
else
  # PC
  export LD_LIBRARY_PATH="$DIR/../../third_party/snpe/x86_64-linux-clang:$DIR/../../openpilot/third_party/snpe/x86_64:$LD_LIBRARY_PATH"
fi
exec ./_modeld
