import os

Import('env', 'arch', 'build_platform', 'cereal', 'messaging', 'common', 'gpucommon', 'visionipc')
lenv = env.Clone()

libs = [cereal, messaging, common, visionipc, gpucommon,
        'OpenCL', 'SNPE', 'symphony-cpu', 'capnp', 'zmq', 'kj', 'yuv']

def get_dlsym_offset():
  """Returns the offset between dlopen and dlsym in libdl.so"""
  import ctypes
  libdl = ctypes.PyDLL('libdl.so')
  dlopen = ctypes.cast(libdl.dlopen, ctypes.c_void_p).value
  dlsym = ctypes.cast(libdl.dlsym, ctypes.c_void_p).value
  return dlsym - dlopen


common_src = [
  "models/commonmodel.cc",
  "runners/snpemodel.cc",
  "transforms/loadyuv.cc",
  "transforms/transform.cc"
]

thneed_src = [
  "thneed/thneed.cc",
  "thneed/serialize.cc",
  "thneed/optimizer.cc",
  "runners/thneedmodel.cc",
]

use_thneed = not GetOption('no_thneed')

if build_platform in ("android_qcom", "linux_qcom"):
  libs += ['gsl', 'CB']
  libs += ['gnustl_shared'] if build_platform == "android_qcom" else ['pthread', 'dl']

  if use_thneed:
    common_src += thneed_src
    dlsym_offset = get_dlsym_offset()
    lenv['CXXFLAGS'].append("-DUSE_THNEED")
    lenv['CXXFLAGS'].append(f"-DDLSYM_OFFSET={dlsym_offset}")
else:
  libs += ['pthread']

  if not GetOption('snpe'):
    del libs[libs.index('SNPE')]
    del libs[libs.index('symphony-cpu')]
    common_src.remove('runners/snpemodel.cc')

    # for generic Linux model runners
    common_src += ['runners/onnxmodel.cc', 'runners/rknnmodel.cc', 'runners/rknn_runtime.c']

    # keep ONNX available for dmonitoring on generic linux
    lenv['CFLAGS'].append("-DUSE_ONNX_MODEL")
    lenv['CXXFLAGS'].append("-DUSE_ONNX_MODEL")

    if arch == "aarch64" and os.path.exists(File("models/supercombo.rknn").abspath):
      libs += ['rknnrt', 'dl']
      lenv['CFLAGS'].append("-DUSE_RKNN_MODEL")
      lenv['CXXFLAGS'].append("-DUSE_RKNN_MODEL")

  if arch == "Darwin":
    # fix OpenCL
    del libs[libs.index('OpenCL')]
    lenv['FRAMEWORKS'] = ['OpenCL']

common_model = lenv.Object(common_src)

# build thneed model
if use_thneed and build_platform in ("android_qcom", "linux_qcom"):
  fn = File("models/supercombo").abspath
  compiler = lenv.Program('thneed/compile', ["thneed/compile.cc"]+common_model, LIBS=libs)
  cmd = f"cd {Dir('.').abspath} && {compiler[0].abspath} {fn}.dlc {fn}_badweights.thneed --binary"

  lib_paths = ':'.join(Dir(p).abspath for p in lenv["LIBPATH"])
  kernel_path = os.path.join(Dir('.').abspath, "thneed", "kernels")
  cenv = Environment(ENV={'LD_LIBRARY_PATH': f"{lib_paths}:{lenv['ENV']['LD_LIBRARY_PATH']}", 'KERNEL_PATH': kernel_path})

  kernels = [os.path.join(kernel_path, x) for x in os.listdir(kernel_path) if x.endswith(".cl")]
  cenv.Command(fn + "_badweights.thneed", [fn + ".dlc", kernels, compiler], cmd)

  from selfdrive.modeld.thneed.weights_fixup import weights_fixup
  def weights_fixup_action(target, source, env):
    weights_fixup(target[0].abspath, source[0].abspath, source[1].abspath)

  env = Environment(BUILDERS = {'WeightFixup' : Builder(action = weights_fixup_action)})
  env.WeightFixup(target=fn + ".thneed", source=[fn+"_badweights.thneed", fn+".dlc"])


lenv.Program('_dmonitoringmodeld', [
    "dmonitoringmodeld.cc",
    "models/dmonitoring.cc",
  ]+common_model, LIBS=libs)

lenv.Program('_modeld', [
    "modeld.cc",
    "models/driving.cc",
  ]+common_model, LIBS=libs)
